### ISSUE TITLE
Using as DLNA receiver

### ISSUE THREAD

**Issue by nyanloutre** [snoopy86/logitechmediaserver#2]
Hello,

I try to use your image with my Squeezebox Radio and play some albums with Emby (Media server with DLNA capabilities). However after each song LMS is pausing the music and is doesn't play the next song of the album. I've also tested with BubbleUpnp (Android) and have the same result.
Do you have any solution by any chance ?

Paul

**Comment by snoopy86** [comment]
Closing this as play trough DLNA is working.
