### ISSUE TITLE
Unable to run Spotty or import from MusicIP

### ISSUE THREAD

**Issue by Bodge-IT** [snoopy86/logitechmediaserver#3]
Hi, thanks for the container!
I changed to this from Qviksilver's container cos I'd like to use Spotty.
Can't seem to get it going plugin just tells me there must be something wrong with OS.
My container is running on container linux CoreOS.  I can't seem to see any realated errors in the log.

[Fixed]:Also I'm using MusicIP and that no longer seems to be able to import from musicip which is in another container.  Do I need to add something to the config to access the MusicIp container on port 10002.

Sorry, I'm notvery  container savvy.  If there's anything else I can provide to help you help me please let me know.

Info:
CoreOS 1688.5.3
Operating system: Debian / x86_64-linux

Helper Applications Folder:
/usr/share/squeezeboxserver/Bin/x86_64-linux
/usr/share/squeezeboxserver/Bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/config/cache/InstalledPlugins/Plugins/CastBridge/Bin
/config/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux
/config/cache/InstalledPlugins/Plugins/Spotty/Bin
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.6) 2.19 

I'm using the /mnt/media/music location instead of /musicso that it concurrs with MusicIP mixes.
Any help would be appeciated.

Update:
Scratch that, I got MusicIP working, just Spotty to fix.

**Comment by snoopy86** [comment]
Closing this. Spotify plugin on LMS is working correctly.
